region                = "ap-south-1"
vpc_cidr              = "10.0.0.0/16"
vpc_name              = "dev_main"
private_subnet_1_cidr = "10.0.1.0/24"
private_subnet_1_name = "dev_main_private_subnet_1_name"
public_subnet_1_name  = "dev_main_public_subnet_1_name"
public_subnet_1_cidr  = "10.0.20.0/24"
igw_name              = "dev_main_igw_name"
public_rt_name        = "dev_main_public_rt_name"
environment           = "dev"
availability_zone     = ["ap-south-1a", "ap-south-1b"]
ami_id                = "ami-0ced6a024bb18ff2e"
key_name              = "master-server"
instance_name         = "dev-main-server"
instance_type         = "t2.micro"
disk_size             = 8
sg_name               = "dev-security-group"
sg_desc               = "Security group for dev environment"
sg_cidr_blocks        = ["0.0.0.0/0"]